name: sport_manager
description: This is an application that allows you to add sports data in the Health application for tennis and dance (Test only on iOS).

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  health: ^8.0.0
  google_fonts: ^6.1.0
  ionicons: ^0.2.2
  shared_preferences: ^2.2.1
  intl: ^0.18.1
  lottie: ^2.6.0
  flutter_localizations:
    sdk: flutter
  audioplayers: ^5.1.0
  geolocator: ^10.1.0
  flutter_tts: ^3.8.3
  flutter_local_notifications: ^15.1.1
  flutter_native_timezone: ^2.0.0
  timezone: ^0.9.2
  rxdart: ^0.27.7
  flutter_app_badger: ^1.5.0
  flutter_iconly: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3
  rename: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  ios: true
  image_path_ios: "assets/icon.png"

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/audio/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
