name: sport_manager
description: This is an application that allows you to add sports data in the Health application for tennis and dance (Test only on iOS).

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  health: ^4.2.0
  google_fonts: ^3.0.1
  ionicons: ^0.2.1
  shared_preferences: ^2.0.16
  intl: ^0.17.0
  lottie: ^2.2.0
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  rename: ^2.1.1
  flutter_launcher_icons: ^0.11.0

flutter_icons:
  ios: true
  image_path_ios: "assets/icon.png"

flutter:

  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
