name: sport_manager
description: This is an application that allows you to add sports data in the Health application for tennis and dance (Test only on iOS).

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  health: ^7.0.1
  google_fonts: ^5.1.0
  ionicons: ^0.2.2
  shared_preferences: ^2.2.0
  intl: ^0.18.0
  lottie: ^2.5.0
  flutter_localizations:
    sdk: flutter
  audioplayers: ^5.0.0
  geolocator: ^9.0.2
  flutter_tts: ^3.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2
  rename: ^2.1.1
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  ios: true
  image_path_ios: "assets/icon.png"

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/audio/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
